spring:
  application:
    name: day7-springboot
  datasource:
    url: jdbc:mysql://localhost:3306/bootcamp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "123456"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
